### ISSUE TITLE
Why do u use Rsocket

### ISSUE THREAD

**Issue by HelloTo4x** [bitnami-labs/bitnami-docker-template#1]
Hi,i am reading your code, why do you use Rsocket instead of other protocols like gRPC or socket, websocket... What is your use case which you use Rsocket, thank you so much

**Comment by carrodher** [comment]
Please note this is a generic repo used as a template, could you please post your question in the specific `bitnami/bitnami-docker-*` repository of the container you're using?

**Comment by HelloTo4x** [comment]
u mean u write for docker, right
